[package]
name = "rust"
version = "0.1.0"
authors = ["Eric Burden <eric.w.burden@gmail.com>"]
edition = "2018"

[dev-dependencies]
criterion = "0.3"
rand = "0.8.4"

[[bench]]
name = "benchmarks"
harness = false

[dependencies]
rdxsort = "0.3.0"
