[package]
name = "rust"
version = "0.1.0"
authors = ["Eric Burden <eric.w.burden@gmail.com>"]
edition = "2018"

[lib]
name = "mylib"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/bin.rs"

[dependencies]
rand = "0.8.4"
